package org.interpss.agent.report;

import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.jupiter.api.Assumptions.assumeTrue;

import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Clock;
import java.time.Instant;
import java.time.ZoneId;
import java.util.List;
import java.util.regex.Pattern;
import java.util.stream.Collectors;

import org.interpss.agent.support.ReportTestSupport;
import org.interpss.agent.util.ProjectPaths;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

class ReportGoldenTest {

    private static final Clock FIXED_CLOCK =
            Clock.fixed(Instant.parse("2020-01-01T12:00:00Z"), ZoneId.of("UTC"));

    @TempDir
    Path tempDir;

    @Test
    void nercReport_matchesGoldenFileForIeee14() throws Exception {
        ProjectPaths paths = ReportTestSupport.createReportProjectLayout(tempDir);
        ReportTestSupport.installFixtures(paths, "ieee14", ReportTestSupport.IEEE14_RESULT);
        ReportConfig config = ReportConfig.load(paths.projectRoot());

        String expected = normalizeVolatileLines(ReportTestSupport.readGolden("ieee14_nerc.md"));
        NercTplReportGenerator.ReportResult result = NercTplReportGenerator.generate(
                paths, config, "IEEE 14-Bus System", ReportTestSupport.IEEE14_RESULT, FIXED_CLOCK);
        assertThat(normalizeVolatileLines(result.markdown())).isEqualTo(expected);
    }

    @Test
    void aclfReport_matchesGoldenFileForIeee118() throws Exception {
        ProjectPaths paths = ReportTestSupport.createReportProjectLayout(tempDir);
        ReportTestSupport.installFixtures(paths, "ieee118", ReportTestSupport.IEEE118_RESULT);
        ReportConfig config = ReportConfig.load(paths.projectRoot());

        String expected = normalizeVolatileLines(ReportTestSupport.readGolden("ieee118_aclf.md"));
        AclfReportGenerator.ReportResult result = AclfReportGenerator.generate(
                paths, config, "IEEE-118 System", ReportTestSupport.IEEE118_RESULT, null, FIXED_CLOCK);
        assertThat(normalizeVolatileLines(result.markdown())).isEqualTo(expected);
    }

    @Test
    void nercReport_matchesGoldenFileForIeee118() throws Exception {
        ProjectPaths paths = ReportTestSupport.createReportProjectLayout(tempDir);
        ReportTestSupport.installFixtures(paths, "ieee118", ReportTestSupport.IEEE118_RESULT);
        ReportConfig config = ReportConfig.load(paths.projectRoot());

        String expected = normalizeVolatileLines(ReportTestSupport.readGolden("ieee118_nerc.md"));
        NercTplReportGenerator.ReportResult result = NercTplReportGenerator.generate(
                paths, config, "IEEE 118-bus", ReportTestSupport.IEEE118_RESULT, FIXED_CLOCK);
        assertThat(normalizeVolatileLines(result.markdown())).isEqualTo(expected);
    }

    @Test
    void updateGoldenReports() throws Exception {
        assumeTrue("true".equals(System.getProperty("updateGolden")),
                "Set -DupdateGolden=true to regenerate report-golden/*.md");

        ProjectPaths paths = ReportTestSupport.createReportProjectLayout(tempDir);
        ReportConfig config = ReportConfig.load(paths.projectRoot());

        ReportTestSupport.installFixtures(paths, "ieee14", ReportTestSupport.IEEE14_RESULT);
        Files.writeString(ReportTestSupport.goldenPath("ieee14_nerc.md"),
                NercTplReportGenerator.generate(
                        paths, config, "IEEE 14-Bus System", ReportTestSupport.IEEE14_RESULT, FIXED_CLOCK)
                        .markdown());

        ReportTestSupport.installFixtures(paths, "ieee118", ReportTestSupport.IEEE118_RESULT);
        Files.writeString(ReportTestSupport.goldenPath("ieee118_aclf.md"),
                AclfReportGenerator.generate(
                        paths, config, "IEEE-118 System", ReportTestSupport.IEEE118_RESULT, null, FIXED_CLOCK)
                        .markdown());
        Files.writeString(ReportTestSupport.goldenPath("ieee118_nerc.md"),
                NercTplReportGenerator.generate(
                        paths, config, "IEEE 118-bus", ReportTestSupport.IEEE118_RESULT, FIXED_CLOCK)
                        .markdown());
    }

    private static String normalizeVolatileLines(String markdown) {
        List<String> lines = markdown.lines().collect(Collectors.toList());
        Pattern reportDate = Pattern.compile("\\| \\*\\*Report Date\\*\\* \\| .* \\|");
        Pattern generatedBy = Pattern.compile("\\| Generated By \\| .* \\|");
        return lines.stream()
                .map(line -> {
                    if (reportDate.matcher(line).matches()) {
                        return "| **Report Date** | FIXED |";
                    }
                    if (generatedBy.matcher(line).matches()) {
                        return "| Generated By | FIXED |";
                    }
                    return line;
                })
                .collect(Collectors.joining("\n"));
    }
}
